

----LAB-9------set operator set operator 

CREATE TABLE COMPUTER
(
	 RollNo Int,
	 Name varchar (50) 
)
CREATE TABLE ELECTRICAL
(
	 RollNo Int,
	 Name varchar (50) 
)
INSERT INTO COMPUTER
	VALUES(101,'AJAY'),
		  (109, 'Haresh'),
		  (115 ,'Manish')
INSERT INTO ELECTRICAL
	VALUES(105 ,'Ajay'),
		  (107 ,'Mahesh'),
		  (115 ,'Manish')


--SELECT NAME FROM COMPUTER
--UNION

--SELECT * FROM COMPUTER

--SELECT * FROM ELECTRICAL

--1. 
SELECT NAME FROM COMPUTER
	UNION
	SELECT NAME FROM ELECTRICAL

--2.
 SELECT NAME FROM COMPUTER
	UNION ALL 
	SELECT NAME FROM ELECTRICAL

--3.
 SELECT NAME FROM COMPUTER
	INTERSECT
	SELECT NAME FROM ELECTRICAL

--4.
	SELECT NAME FROM COMPUTER
	EXCEPT
	SELECT NAME FROM ELECTRICAL 

--5.
 SELECT NAME FROM ELECTRICAL
	EXCEPT
	SELECT NAME FROM COMPUTER 

--6.
 SELECT *FROM COMPUTER
	UNION
	SELECT * FROM ELECTRICAL

--7.
 SELECT * FROM COMPUTER
	INTERSECT
	SELECT * FROM ELECTRICAL


--SELECT INTO  

---LAB-9 ------

CREATE TABLE CRICKET
( Name varchar (50),
  City varchar (50), 
  Age Int
)
INSERT INTO CRICKET
VALUES('Sachin Tendulkar', 'Mumbai', 30),	
	  ('Rahul Dravid ','Bombay', 35),
      ('M. S. Dhoni' ,'Jharkhand', 31),  
      ('Suresh Raina' ,'Gujarat' ,30)

 SELECT * FROM CRICKET


 --1.
  SELECT * INTO WORDCUP FROM CRICKET

 --2.
  SELECT NAME,CITY INTO T20 FROM CRICKET
	WHERE CITY='SURAT';

 --3.
  SELECT * INTO IPL FROM CRICKET
	WHERE 1=2;

 --4.
 SELECT *INTO IPL FROM CRICKET
	WHERE NAME LIKE '_A_____%';

 --5.
 TRUNCATE TABLE IPL 

 --6.
 DELETE FROM CRICKET 
	WHERE CITY='JHARKHAND'

 --7.
 SP_RENAME 'IPL','IPL2018'

 --8.
 DROP TABLE T20
